// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MvvmHelpKit
{
    internal sealed partial class Vsix
    {
        public const string Id = "MvvmHelpKit.d4a6bdf5-84e5-433c-a698-1fa07db3463f";
        public const string Name = "Mvvm Help Kit";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Jack Hamilton";
        public const string Tags = "";
    }
}
